name: gaspipe_client build & test

on:
  push:
    paths-ignore:
      - 'LICENSE'
      - '*.md'
    branches:
      - master
  pull_request:
    paths-ignore:
      - 'LICENSE'
      - '*.md'

jobs:
  build:
    # runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # os: [ 'ubuntu-latest', 'windows-latest', 'macOS-latest' ]
        nim: [ 'stable', 'devel' ]
    name: Nim ${{ matrix.nim }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Cache nimble
        id: cache-nimble
        uses: actions/cache@v1
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}
        if: runner.os != 'Windows'
      - uses: jiro4989/setup-nim-action@v1
      - name: Export PATH
        run: export PATH=$HOME/.nimble/bin:$PATH
        if: runner.os != 'Windows'
      - name: Build fsigner
        run: nimble build -Y
      - name: Test fsigner
        run: nimble test -Y
  